### ISSUE TITLE
Systemtests use test input and expected output in test method

### ISSUE THREAD

**Issue by Grimrath** [Darkfrobozz/inlupp4#19]
A trend I've noticed is that many of the system tests I've written has gotten smaller and smaller when attempting to isolate a single fault source to a single test case (perhaps I'm doing systemtests wrong?). This makes it so the number of input and expected output files greatly increase.

To better separate the concern of system testing (at least for smaller inputs) could be to add methods that create, read and remove temporary input and output files from strings for each test method.

What do you think?

**Comment by Darkfrobozz** [comment]
I like this idea, I reworked the code to introduce a stdin and stdAns, These are used locally and emptied after each test.
dfd299cedc7a6640e5952ab064dbec9c79aee903
There is a helper function there, that works through two queues, one to add prompts and one to add expected answers to those prompts. A quit command is added automatically at the end.
Moreover, a small example is provided in the test shortArthimetics on how to use it.
